from . import db


class MonthlyReport(db.Model):
    __tablename__ = "monthly_reports"

    id = db.Column(db.Integer, primary_key=True)
    emp_id = db.Column(db.Integer, db.ForeignKey("employees.id"), nullable=False, index=True)
    report_month = db.Column(db.String(7), nullable=False, index=True)  # YYYY-MM

    agg_01 = db.Column(db.Float)
    agg_02 = db.Column(db.Float)
    agg_03 = db.Column(db.Float)
    agg_04 = db.Column(db.Float)
    agg_05 = db.Column(db.Float)
    agg_06 = db.Column(db.Float)
    agg_07 = db.Column(db.Float)
    agg_08 = db.Column(db.Float)
    agg_09 = db.Column(db.Float)
    agg_10 = db.Column(db.Float)
    agg_11 = db.Column(db.Float)
    agg_12 = db.Column(db.Float)
    agg_13 = db.Column(db.Float)
    agg_14 = db.Column(db.Float)
    agg_15 = db.Column(db.Float)
    agg_16 = db.Column(db.Float)
    agg_17 = db.Column(db.Float)
    agg_18 = db.Column(db.Float)
    agg_19 = db.Column(db.Float)
    agg_20 = db.Column(db.Float)
    agg_21 = db.Column(db.Float)
    agg_22 = db.Column(db.Float)
    agg_23 = db.Column(db.Float)
    agg_24 = db.Column(db.Float)
    agg_25 = db.Column(db.Float)
    agg_26 = db.Column(db.Float)
    agg_27 = db.Column(db.Float)
    agg_28 = db.Column(db.Float)
    agg_29 = db.Column(db.Float)
    agg_30 = db.Column(db.Float)
    agg_31 = db.Column(db.Float)
    agg_32 = db.Column(db.Float)
    agg_33 = db.Column(db.Float)
    agg_34 = db.Column(db.Float)
    agg_35 = db.Column(db.Float)
    agg_36 = db.Column(db.Float)
    agg_37 = db.Column(db.Float)
    agg_38 = db.Column(db.Float)
    agg_39 = db.Column(db.Float)
    agg_40 = db.Column(db.Float)
    agg_41 = db.Column(db.Float)
    agg_42 = db.Column(db.Float)
    agg_43 = db.Column(db.Float)
    agg_44 = db.Column(db.Float)
    agg_45 = db.Column(db.Float)
    agg_46 = db.Column(db.Float)
    agg_47 = db.Column(db.Float)
    agg_48 = db.Column(db.Float)
    agg_49 = db.Column(db.Float)
    agg_50 = db.Column(db.Float)
    agg_51 = db.Column(db.Float)
    agg_52 = db.Column(db.Float)
    agg_53 = db.Column(db.Float)
    agg_54 = db.Column(db.Float)
    agg_55 = db.Column(db.Float)
    agg_56 = db.Column(db.Float)
    agg_57 = db.Column(db.Float)
    agg_58 = db.Column(db.Float)
    agg_59 = db.Column(db.Float)
    agg_60 = db.Column(db.Float)
    agg_61 = db.Column(db.Float)
    agg_62 = db.Column(db.Float)
    agg_63 = db.Column(db.Float)
    agg_64 = db.Column(db.Float)
    agg_65 = db.Column(db.Float)
    agg_66 = db.Column(db.Float)
    agg_67 = db.Column(db.Float)
    agg_68 = db.Column(db.Float)
    agg_69 = db.Column(db.Float)
    agg_70 = db.Column(db.Float)
    agg_71 = db.Column(db.Float)
    agg_72 = db.Column(db.Float)
    agg_73 = db.Column(db.Float)
    agg_74 = db.Column(db.Float)
    agg_75 = db.Column(db.Float)
    agg_76 = db.Column(db.Float)
    agg_77 = db.Column(db.Float)
    agg_78 = db.Column(db.Float)
    agg_79 = db.Column(db.Float)
    agg_80 = db.Column(db.Float)
    agg_81 = db.Column(db.Float)
    agg_82 = db.Column(db.Float)
    agg_83 = db.Column(db.Float)
    agg_84 = db.Column(db.Float)

    raw_data = db.Column(db.JSON, default=dict)
    employee_raw_data = db.Column(db.JSON, default=dict)
    manager_raw_data = db.Column(db.JSON, default=dict)

    employee = db.relationship("Employee", back_populates="monthly_reports")

    __table_args__ = (db.UniqueConstraint("emp_id", "report_month", name="uq_emp_report_month"),)
